### ISSUE TITLE
Search for free/CORS api's for jokes and facts

### ISSUE THREAD

**Issue by kittykatt210** [kittykatt210/socially-awkward#2]

**Comment by kittykatt210** [comment]
https://uselessfacts.jsph.pl

**Comment by florezf90** [comment]
https://api-ninjas.com/api/facts

https://api-ninjas.com/api/jokes

https://api-ninjas.com/api/historicalevents

https://sv443.net/jokeapi/v2/

https://api.chucknorris.io/

These are the API's that we have found so far, we have the initiative of using as many Ninja's API's as possible for compatibility purposes
