### ISSUE TITLE
Create wireframe for page

### ISSUE THREAD

**Issue by kittykatt210** [kittykatt210/socially-awkward#4]

**Comment by florezf90** [comment]
First idea for website framework: https://wireframe.cc/1gxJ6t

Waiting for teammates' approval and/or suggestions

**Comment by florezf90** [comment]
Smalls adjustments were made to the initial framework based on teammates' input, simplified layouts by deleting extra "fav" lists in every section of the page, and created a button that will take the user to one single tab that will display their saved choices
